# -*- coding: utf-8 -*-
"""transferlearning.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oD3EweYMUiNQi9TGbXH8BHenN9vKCLxB
"""

i#loading basic dependencies 
import pandas as pd
import numpy as np
import os
import keras
import matplotlib.pyplot as plt
from keras.layers import Dense,GlobalAveragePooling2D
from keras.applications import MobileNet
from keras.preprocessing import image
from keras.applications.mobilenet import preprocess_input
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.optimizers import Adam
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,confusion_matrix
from keras.models import load_model
from PIL import Image
import numpy as np
from skimage import transform

#function to load file 

def load(filename):
   np_image = Image.open(filename)
   np_image = np.array(np_image).astype('float32')/255
   np_image = transform.resize(np_image, (224, 224, 3))
   np_image = np.expand_dims(np_image, axis=0)
   return np_image

#provide image address as parameter
img=load("img.jpg")



#loading trained model weights
model = load_model('transfer_learning.h5')
y=model.predict(img)
print(y)