# -*- coding: utf-8 -*-
"""VGG16model.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLaIGA-XgtIbU2t_ZgepT3gxVY7RIgym
"""

import cv2
from PIL import Image
import matplotlib.pyplot as plt 
import sklearn
import imutils 
import os 
import numpy as np
from IPython.display import Image, display
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
from keras.utils import  np_utils
import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Dropout
from keras.layers import Conv2D,MaxPool2D,ZeroPadding2D,Convolution2D,MaxPooling2D
from keras import backend as K
from keras.layers import BatchNormalization
from keras.optimizers import SGD,RMSprop
from keras.models import load_model




#insert image addess
img_address=""

data=[]
img_read=plt.imread(img_address)
img_resize=cv2.resize(img_read,(50,50))
img_ch = cv2.cvtColor(img_resize, cv2.COLOR_BGR2GRAY)
img_array=img_to_array(img_ch)
data.append(img_array)

image_data=np.array(data)

model = load_model('vgg_model.h5')
y=model.predict(img)
#0 for Normal Lungs
#1 for infected lungs
print(y)

